//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mohamed_Projet_426
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTerritory
    {
        public int EmployeID { get; set; }
        public string TerritoryID { get; set; }
    }
}
